# Generated by Django 4.2.3 on 2023-08-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Фото новости')),
                ('title', models.CharField(max_length=55, verbose_name='Загаловок новости')),
                ('description', models.TextField(verbose_name='Описание новости')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Доп фото для новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Доп фото новости',
                'verbose_name_plural': 'Доп фото новости',
            },
        ),
    ]
