# Generated by Django 4.2.3 on 2023-07-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Доп фото для новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Доп фото новости',
                'verbose_name_plural': 'Доп фото новости',
            },
        ),
    ]
