# Generated by Django 4.2.4 on 2023-08-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_ky',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='created_ru',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Загаловок новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Загаловок новости'),
        ),
    ]
