# Generated by Django 4.2.4 on 2023-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_created_ky_news_created_ru_news_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Доп Жаңылыктын сүрөтү', 'verbose_name_plural': 'Доп Жаңылыктын сүрөтү'},
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Жаңылыктын сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Жаңылыктын сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Жаңылыктын сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news_images/', verbose_name='Жаңылыктын сүрөтү'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Жаңылыктын башы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Жаңылыктын башы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Жаңылыктын башы'),
        ),
    ]
