# Generated by Django 4.2.4 on 2023-08-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_media_options_alter_news_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description_ky',
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(default=1, verbose_name='Жаңылыктын сүрөттөлүшү'),
            preserve_default=False,
        ),
    ]
