# Generated by Django 4.2.4 on 2023-08-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct',
            name='name_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Название структуры'),
        ),
        migrations.AddField(
            model_name='struct',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название структуры'),
        ),
        migrations.AddField(
            model_name='team',
            name='full_name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='team',
            name='full_name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='team',
            name='job_title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='team',
            name='job_title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
