# Generated by Django 4.2.4 on 2023-08-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_struct_name_ky_struct_name_ru_team_full_name_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('text_ky', models.CharField(max_length=5000, null=True)),
                ('text_ru', models.CharField(max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Главная информация',
                'verbose_name_plural': 'Главная информация',
            },
        ),
    ]
