# Generated by Django 4.2.4 on 2023-08-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_tourism'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=25)),
                ('phone2', models.CharField(max_length=25)),
                ('fax', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
