# Generated by Django 4.2.4 on 2023-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininfo',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='tourism',
            name='text_ky',
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='text_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourism',
            name='text_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
