# Generated by Django 4.2.4 on 2023-08-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_remove_maininfo_text_ky_remove_tourism_text_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='email',
        ),
    ]
