# Generated by Django 4.2.4 on 2023-08-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_remove_team_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='struct',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='struct',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='struct',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
