# Generated by Django 4.2.4 on 2023-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_struct_description_struct_description_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сorruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_ru', models.TextField()),
            ],
            options={
                'verbose_name': 'Информациия о противодействии коррупции',
                'verbose_name_plural': 'Информациия о противодействии коррупции',
            },
        ),
    ]
