# Generated by Django 4.2.4 on 2023-08-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_сorruption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сorruption',
            new_name='Corruption',
        ),
    ]
