# Generated by Django 4.2.4 on 2023-08-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_rename_сorruption_corruption'),
    ]

    operations = [
        migrations.CreateModel(
            name='GosLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_ky', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Ссылка на гос сайт',
                'verbose_name_plural': 'Ссылки на гос сайты',
            },
        ),
    ]
