# Generated by Django 4.2.4 on 2023-08-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_goslinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='resume',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='resume_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='resume_ru',
            field=models.TextField(null=True),
        ),
    ]
