# Generated by Django 4.2.4 on 2023-08-17 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_team_resume_team_resume_ky_team_resume_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourism_media/', verbose_name='Фото для Туризма')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='team.tourism')),
            ],
            options={
                'verbose_name': 'Фото для туризма',
                'verbose_name_plural': 'Фото для туризма',
            },
        ),
    ]
