# Generated by Django 4.2.4 on 2023-08-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_ru', models.TextField()),
            ],
            options={
                'verbose_name': 'Фонд развития',
                'verbose_name_plural': 'Фонды развития',
            },
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_ru', models.TextField()),
            ],
            options={
                'verbose_name': 'Политика конфеденцальности',
                'verbose_name_plural': 'Политика конфеденцальности',
            },
        ),
        migrations.CreateModel(
            name='StateSymbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_ru', models.TextField()),
            ],
            options={
                'verbose_name': 'Гос. символ',
                'verbose_name_plural': 'Гос. символы',
            },
        ),
    ]
